# Generated by Django 2.1.2 on 2018-10-23 16:18

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20181023_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
